# Generated by Django 2.1 on 2018-08-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='muse_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC_address', models.CharField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rasp_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('ip_address', models.CharField(max_length=24)),
                ('connected_muse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mpcontroller.muse_device')),
            ],
        ),
    ]
