# Generated by Django 2.1 on 2018-08-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpcontroller', '0002_auto_20180806_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasp_device',
            name='connected_muse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpcontroller.muse_device'),
        ),
    ]
