# Generated by Django 2.1 on 2018-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcontroller', '0003_auto_20180806_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasp_device',
            name='id',
        ),
        migrations.AlterField(
            model_name='rasp_device',
            name='ip_address',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
