# Generated by Django 2.1 on 2018-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpcontroller', '0004_auto_20180806_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='muse_device',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
