# Generated by Django 2.1 on 2018-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpcontroller', '0007_auto_20180807_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muse_device',
            old_name='MAC_address',
            new_name='mac_address',
        ),
    ]
